### ISSUE TITLE
Would 💗 to see a screenshot, maybe in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [WhitemuTeam/Study-To-Do#2]
It looks like you've created quite an application.  Do you have any screenshots you can share?  I would love to see what you've made.

Sorry you didn't win the competition
![image](https://user-images.githubusercontent.com/46163555/182044157-31f8ea34-a0db-4be3-8b31-fd4a24b2fd4a.png)

I noticed at the bottom of your readme:
`The source code of this application may not be distributed in any way

`The source code of this application may not be distributed in any way`

There's no license.md file.  Do you have any plans on licensing it in any way.  It's a little confusing to see the phrase
`" has made it open source on Github "`

There are some licensing requirements by the packages you've used to implement your project that you may want to take a closer look at.

**Comment by Moemu** [comment]
Wow, thank you for your message. I reconsidered the issue of open source license. At first, I was concerned about whether others would use my source code to make simple changes and participate in the competition, which would have an impact on my competition. Now I think maybe I need to release the license. Thank you for your attention.

**Comment by Moemu** [comment]
In addition, I noticed the problem about screenshots. Well, as for Chinese programs, non Chinese people may not be able to read the text on the screenshots. I am considering L10N support. I am now preparing screenshots. Thank you for your feedback.

**Comment by PySimpleGUI** [comment]
>  I was concerned about whether others would use my source code to make simple changes and participate in the competition

AHHHHHHHHHHHHHHHHHH!!!!  

This totally makes sense!  Thank you for explaining.  ![image](https://user-images.githubusercontent.com/46163555/182105363-b9429575-6995-49be-a4d6-559285f0ebf7.png)


Knowing this, I'm a bit surprised you posted any of your code publicly.

![image](https://user-images.githubusercontent.com/46163555/182104423-e6b532d2-9ad5-49e9-b36a-8d4e1a77f423.png)

I wouldn't worry about the readability of the text.  In my opinion, it's the overall look, design, layout, etc, that are the important things that a screenshot communicates.   The creative and artist inspiration alone can be quite informative.  Not being able to read the text may not be a problem at all.

Thank you for the incredibly fast response that provided context that I was missing or not understanding.

**Comment by Moemu** [comment]
How to say, this is really a problem that people will think about. I am a person who loves open source. Most of the programs I make will be open source, so that people can give feedback to make my programs better.

**Comment by Moemu** [comment]
Screenshots have now been added. Thank you for waiting. You can now view these screenshots in the [Program documentation](https://doc.muspace.top/#/zh-cn/Program/Study-To-Do?id=%e5%b1%8f%e5%b9%95%e6%88%aa%e5%9b%be). The language of these documents is Chinese (Simplified), so it may be difficult to read the above text. Anyway, I'm sorry to keep you waiting so long. Thank you for your support

**Comment by PySimpleGUI** [comment]
No need for "sorry" at all!  I appreciate you taking the time to add them.  They're for you and your visitors, not me.  You actually got them added quite quickly.  They look GREAT!  Much more there than I realized.  It's exciting to see what you've made.  

Congratulation on a great job!  Your project is a winner to me!!  

![image](https://user-images.githubusercontent.com/46163555/184194697-2e0ba2b6-d393-464d-9900-1a45cdd43117.png)

The impact you have on others is greater than an award.  You're having a bigger impact than an award could maybe represent.  I understand the disappointment of "losing a competition" though.  You've got a lot to be proud of and really hope you consider what you've made a success regardless of what a panel of judges may have thought.

Thank you for the conversation.  I appreciate you taking the time to have one, and the patience to have it in my language.
![image](https://user-images.githubusercontent.com/46163555/184194431-d064be62-9fc4-4537-bcc4-488758c0d98f.png)
